// all this stuff is client side

lvl1Data = [
  "je ne suis pas une tondeuse",
  "je ne suis pas une brosse à dents connectée",
  "je ne suis pas une imprimante qui commande toute seule ses cartouches de toner sur internet quand il n'y a soi-disant plus d'encre",
  "je ne suis pas l'imprimante qui est tombée sur le site du théâtre par hasard et aurait décidé de venir voir cette performance par curiosité",
  "je ne suis pas un objet qui, obéissant aux lois de la gravité, aurait exercé une pression sur le bouton de la souris en chutant dessus",
  "je ne suis pas un rat, qui après un million d'années d'évolution aurait développé un bras et un pouce opposable et aurait cliqué sur le bouton",
  "je ne suis pas le changement climatique qui aurait fait monter le niveau de la mer jusqu'à cliquer sur le bouton ",
  "je ne suis pas la volonté de dieu qui est intervenue pour cliquer sur le bouton",
  "je ne suis pas le bouton qui a déclaré que dieu était mort et s'est auto cliqué dessus par révolte",
  "je ne suis pas un bug informatique qui aurait fait que la case à cocher aurait cru de bonne foi qu'on lui avait cliqué dessus, alors que personne ne lui avait en fait cliqué dessus.",
  "je ne suis pas la case à cocher qui, par vanité, aurait prétendu qu'on lui avait cliqué dessus alors que personne n'avait jamais cliqué dessus.",
  "je ne suis pas une personne travaillant dans une ferme à clic et payée 1 euro de l'heure pour cliquer sur le bouton pour le compte de personnes ne voulant en aucun cas cliquer sur le bouton.",
  "je déclare que je clique librement sur ce bouton sans aucune contrainte.",
  "ce sont bien les signaux électriques de mon cerveau qui ont commandé à mon doigt d'enfoncer le bouton de la souris",
  "ce ne sont pas les signaux électriques d'une autre personne qui ont commandé à mon doigt d'enfoncer le bouton de la souris",
  "c'est mon cerveau, c'est mon doigt ",
  "coucou c'est moi",
  "je suis qui je suis",
  "je pense ce que je pense ",
  "mes pensées sont nées dans mon cerveau",
  "je ne répète pas des sons aux hasard depuis des années afin de cacher le fait que je n'arrive pas à produire des pensées dans mon cerveau",
  "je clique sur le bouton parce que je suis gentil.le",
  "je clique peut-être sur le bouton à cause du cadre autoritaire de l'institution culturelle dans laquelle je me trouve actuellement",
  "ok je clique sur le bouton pour faire plaisir à Samuel",
  "Samuel est content",
];
